### ISSUE TITLE
Meld dropdown usability enhancements

### ISSUE THREAD

**Issue by chairbender** [chairbender/mahjong-eye#11]
- [x] If the meld has been identified, display the identification in the dropdown (i.e. 7s rather than "Meld#")
- [x] If the dropdown selection is changed, automatically update the image to the new value without having to press the "DisplayMeld" or "DisplayReference" or "Display Matches" button.
- [ ] Bonus points / optional - show a preview of the image when hovering over any of the elements in any of the dropdowns - don't require it to be clicked.

**Comment by TheFourBit** [comment]
What are the Check Boxes for

**Comment by chairbender** [comment]
you can check them to mark that they're done

**Comment by TheFourBit** [comment]
oh got it

**Comment by chairbender** [comment]
fyi I added an extra optional thing to try...not sure if there's a way to do that with ComboBox in javafx (see when you are hovering over an item but not yet selecting it)

**Comment by TheFourBit** [comment]
lol that sounds like fxml hell to me

**Comment by TheFourBit** [comment]
I can do DisplayMeld and Display Reference to appear from click in drop...but not Display Matches since there is not associated combo box so I'll check it as done for now but tell me if you had something else in mind

**Comment by chairbender** [comment]
Cool, that's fine

**Comment by chairbender** [comment]
@TheFourBit lmk if you want to try that bonus one, otherwise feel free to close once the code is merged to master
