### ISSUE TITLE
Transfer to JavaFX

### ISSUE THREAD

**Issue by TheFourBit** [chairbender/mahjong-eye#17]
Transfer the UI from fxml to a JavaFX file where it would make it easier to write other UI implementations with the possibility of looking up code examples and references. (Preferably without breaking everything)

**Comment by chairbender** [comment]
I think we don't need to do this, we can combine both approaches. We already can use code examples

**Comment by TheFourBit** [comment]
Code Examples for fxml?

**Comment by TheFourBit** [comment]
how would we run one UI off of JavaFX and fxml

**Comment by chairbender** [comment]
Even java code examples can be used already. There's nothing that fxml is preventing us from doing.
